defaults:
  - dmd_refaligned_ode_warmup_fsdp1.yaml

method:
  params:
    generator_objective: teacher_feature_ste
    teacher_feature_layers: [5, 15, 25]
    teacher_feature_timestep: 0.2
    dfake_gen_update_ratio: 5

optimizer:
  generator:
    type: adamw_schedule_free
    lr: 5.0e-5
    max_grad_norm: 2.83
